name: jackvanham
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8877804910298437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3616125825792551
  lightness: 0.8151895247865468
  saturation: 0.9863135970663279
  rhythmicContrast: 0.1222971158567816
purpose: []
