name: jackvanham
favicon: null
layout_spectrum: 1
typography_spectrum: 0.57832
title: Jack van Ham
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020003'
    - '#525053'
    - '#fefefe'
    - '#f8c075'
    - '#8f8271'
  brandStrength: 0.3616125825792551
  lightness: 0.8151895247865468
  saturation: 0.9863135970663279
  rhythmicContrast: 0.1222971158567816
purpose: []
